name: Build invesalius_cy on Windows

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build_invesalius_cy:
    name: Build invesalius_cy for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            python: '3.8'
            platform_id: win_amd64
            requirements: requirements.txt
          - os: windows-2019
            python: '3.9'
            platform_id: win_amd64
            requirements: requirements_m1.txt
          - os: windows-2019
            python: '3.10'
            platform_id: win_amd64
            requirements: requirements_m1.txt
          - os: windows-2019
            python: '3.11'
            platform_id: win_amd64
            requirements: requirements_m1.txt

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v4
        name: Install Python host for cibuildwheel
        with:
          python-version: ${{ matrix.python }}

        # Visual Studio
      - name: Set up MSVC x64
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build invesalius_cy
        run: |
          $env:NUMPY = (Select-String -Path ${{ matrix.requirements }} -Pattern numpy).Line
          $env:CYTHON = (Select-String -Path ${{ matrix.requirements }} -Pattern cython).Line
          pip install $env:NUMPY
          pip install $env:CYTHON
          python setup.py build_ext --inplace
          mkdir dist/python-${{ matrix.python }}
          cp invesalius_cy/*.pyd dist/python-${{ matrix.python }}

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
          name: compiled_invesalius_cy

  publish:
    needs: [build_invesalius_cy]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Must perform checkout first, since it deletes the target directory
      # before running, and would therefore delete the downloaded artifacts
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

      - name: creating zip
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          zip -r compiled_invesalius_cy.zip compiled_invesalius_cy

      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          files: |
            compiled_invesalius_cy.zip
